-- Selecione o banco
USE [BDTESTE2]
GO

CREATE TABLE ALUNO
(COD_ALUNO INT NOT NULL,
NOM_ALUNO VARCHAR(100) NOT NULL
);

-- Com Schema
CREATE TABLE [dbo].[CURSO]
(
	[COD_CURSO] [INT] NOT NULL,
	[NOM_CURSO] [VARCHAR](100) NOT NULL
)
GO

-- Com filegroup
CREATE TABLE [dbo].[MATRICULA]
(
	[COD_ALUNO] [INT] NOT NULL,
	[COD_CURSO] [INT] NOT NULL,
	[DAT_MATRICULA] [DATETIME] NOT NULL
) ON [PRIMARY]
GO

CREATE SYNONYM TB_ALUNO_NEW FOR ALUNO;

SELECT * FROM ALUNO;

SELECT * FROM TB_ALUNO_NEW;

-- AJUDA

sp_help 'ALUNO'

sp_help 'TB_ALUNO_NEW'

-- FQN Full qualified name

SELECT * FROM MG00NBK6005.BDTESTE2.dbo.ALUNO;