-- Comando DDL DROP utilize com cautela pois o comando é atomico
-- Ele não permite apagar tabelas em uso nem tabelas com chaves estrangeiras no relacionamento
-- É preciso apagar os relacionamentos antes de apagar a tabela

DROP DATABASE BDProducoes1

-- CRIAR BANCO
CREATE DATABASE BDTESTE_DROP
GO

--SELECIONAR BANCO
USE BDTESTE_DROP
GO

CREATE TABLE ALUNO
(
COD_ALUNO INT NOT NULL,
NOM_ALUNO VARCHAR (100) NOT NULL
);

CREATE TABLE CURSO
(
COD_CURSO INT NOT NULL,
NOM_CURSO VARCHAR (100) NOT NULL
)
GO

-- ADICIONAR CHAVE PRIMÁRIA
ALTER TABLE ALUNO
ADD CONSTRAINT PK_ALUNO PRIMARY KEY CLUSTERED
(
	COD_ALUNO
)
GO

ALTER TABLE CURSO
ADD CONSTRAINT PK_CURSO PRIMARY KEY CLUSTERED
(
	COD_CURSO
)
GO

-- ADICIONAR COLUNA COD_CURSO_FK NA TABELA ALUNO
ALTER TABLE ALUNO ADD COD_CURSO_FK INT NOT NULL
GO

-- ALTERAR COLUNA COD_CURSO_FK PARA NÃO NULA
ALTER TABLE ALUNO ALTER COLUMN COD_CURSO_FK INT NOT NULL
GO

-- ADICIONAR CHAVE ESTRANGEIRA COD_CURSO_FK NA TABELA ALUNO
ALTER TABLE ALUNO
ADD CONSTRAINT FK_ALUNO_CURSO FOREIGN KEY
(
COD_CURSO_FK
)REFERENCES CURSO
(
COD_CURSO
)
ON UPDATE NO ACTION
ON DELETE NO ACTION
GO

-- REMOVER SINONIMO
DROP SYNONYM TB_ALUNO_NEW;

-- REMOVER COLUNA (NÃO É UM OBJETO INDEPENDENTE)
ALTER TABLE ALUNO DROP COLUMN NOM_ALUNO;

SP_HELP ALUNO;

-- REMOVER TABELA (COM FK)
DROP TABLE ALUNO;
DROP TABLE CURSO;

-- REMOVER BANCO DE DADOS
USE MASTER;
DROP DATABASE BDTESTE_DROP;

-- REMOVER BANCO DE DADOS QUE ESTÁ SENDO USADO
-- EM OUTRA SESSÃO
CREATE DATABASE BDTESTE;
USE BDTESTE;

CREATE TABLE CURSO
(
	[COD_CURSO] [INT] NOT NULL,
	[NOM_CURSO] [VARCHAR](100) NOT NULL
);

SELECT * FROM CURSO;

USE MASTER;
DROP DATABASE BDTESTE;

-- LISTAR PROCESSOS BLOQUEADOS ANTES DE DROPAR O BD
SELECT * FROM sysprocesses
where blocked <> 0

select * from sys.dm_exec_requests
where blocking_session_id <> 0

-- USAR COMANDO "KILL" PARA FINALIZAR AS CONEXÕES COM O BD QUE DESEJA APAGAR
KILL 55;